theme: jekyll-theme-slate
title: Data Blog
description : Research and discovery on data architecture, stratgey and governance. Includes updates on recent Open Data set publications, practices and usages.